---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: data/galeries
  label: Galeries
  create: all
  match: "**/*"
  templates:
  - add_pictures
- type: directory
  path: data/prestations
  label: Prestations
  create: documents
  match: "**/*"
  templates:
  - new_prestation
upload_dir: public/resources/medias
public_path: "/public/resources/medias"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
